# Generated by Django 5.2 on 2026-03-03 00:24

import django.db.models.deletion
import wardrobe.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('T-Shirts & Tops', 'T-Shirts & Tops'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Dresses', 'Dresses'), ('Skirts', 'Skirts'), ('Jackets & Blazers', 'Jackets & Blazers'), ('Coats & Outerwear', 'Coats & Outerwear'), ('Shorts', 'Shorts'), ('Sweaters & Knitwear', 'Sweaters & Knitwear'), ('Hoodies & Sweatshirts', 'Hoodies & Sweatshirts'), ('Underwear & Loungewear', 'Underwear & Loungewear'), ('Socks', 'Socks'), ('Activewear', 'Activewear'), ('Sleepwear & Robes', 'Sleepwear & Robes')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('garment_photo', models.ImageField(blank=True, null=True, upload_to=wardrobe.models.garment_photo_path)),
                ('care_label_photo', models.ImageField(blank=True, null=True, upload_to=wardrobe.models.care_label_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
