# Generated by Django 5.2 on 2026-03-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(choices=[('T-Shirts & Tops', 'T-Shirts & Tops'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Dresses', 'Dresses'), ('Skirts', 'Skirts'), ('Jackets & Blazers', 'Jackets & Blazers'), ('Coats & Outerwear', 'Coats & Outerwear'), ('Shorts', 'Shorts'), ('Sweaters & Knitwear', 'Sweaters & Knitwear'), ('Hoodies & Sweatshirts', 'Hoodies & Sweatshirts'), ('Underwear & Loungewear', 'Underwear & Loungewear'), ('Socks', 'Socks'), ('Activewear', 'Activewear'), ('Sleepwear & Robes', 'Sleepwear & Robes'), ('Other', 'Other')], max_length=50),
        ),
    ]
