# Generated by Django 5.2 on 2026-03-29 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_add_other_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_ai_json', models.JSONField()),
                ('ai_washing', models.TextField()),
                ('ai_drying', models.TextField()),
                ('ai_ironing', models.TextField()),
                ('ai_bleach', models.TextField()),
                ('ai_is_delicate', models.BooleanField(default=False)),
                ('ai_summary', models.TextField()),
                ('washing', models.TextField()),
                ('drying', models.TextField()),
                ('ironing', models.TextField()),
                ('bleach', models.TextField()),
                ('is_delicate', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('personal_notes', models.TextField(blank=True)),
                ('is_user_edited', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_cache', models.BooleanField(default=False)),
                ('garment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_analysis', to='wardrobe.garment')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=8, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='wardrobe.garment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='wardrobe_us_user_id_722298_idx'), models.Index(fields=['created_at'], name='wardrobe_us_created_dc5447_idx')],
            },
        ),
    ]
