# Generated by Django 5.2 on 2026-04-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_careanalysis_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='careanalysis',
            name='failure_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
